# Generated by Django 5.2.16 on 2026-08-09 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_invitation_brevo_message_id'),
        ('decisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=40)),
                ('supplier_id', models.UUIDField()),
                ('supplier_name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PARTIALLY_RECEIVED', 'Partiellement reçue'), ('RECEIVED', 'Réceptionnée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=24)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_code', models.CharField(blank=True, max_length=40)),
                ('product_name', models.CharField(max_length=180)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='decisions.purchaseorder')),
                ('source_draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='decisions.restockdraft')),
            ],
            options={
                'db_table': 'procurement_order_items',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_id', models.UUIDField(unique=True)),
                ('receipt_number', models.CharField(max_length=40)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='decisions.purchaseorder')),
            ],
            options={
                'db_table': 'procurement_order_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'status', 'created_at'], name='proc_order_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='unique_company_purchase_order_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product_id'), name='unique_product_per_purchase_order'),
        ),
    ]
