# Generated by Django 5.2.16 on 2026-08-02 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=180, verbose_name='nom du dépôt')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('timezone', models.CharField(default='Africa/Bamako', max_length=50, verbose_name='fuseau horaire')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
                'verbose_name': 'dépôt',
                'verbose_name_plural': 'dépôts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('ANALYST', 'Analyste'), ('VIEWER', 'Consultation')], default='VIEWER', max_length=12)),
                ('status', models.CharField(choices=[('INVITED', 'Invité'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REVOKED', 'Révoqué')], default='ACTIVE', max_length=12)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_memberships',
                'verbose_name': 'accès au dépôt',
                'verbose_name_plural': 'accès aux dépôts',
                'indexes': [models.Index(fields=['user', 'status'], name='membership_user_status_idx'), models.Index(fields=['company', 'role'], name='membership_company_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_membership')],
            },
        ),
    ]
