# Generated by Django 5.2.16 on 2026-08-09 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_invitation_brevo_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitation',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('PHONE', 'Téléphone')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='companyinvitation',
            index=models.Index(fields=['phone', 'status'], name='invitation_phone_status_idx'),
        ),
    ]
