# Generated by Django 5.2.16 on 2026-08-02 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def protect_audit_logs(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION prevent_audit_log_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF current_setting('app.audit_maintenance', TRUE) = 'on' THEN
                IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'audit_logs is append-only';
        END;
        $$;
        CREATE TRIGGER audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
    """)


def remove_audit_protection(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs")
    schema_editor.execute("DROP FUNCTION IF EXISTS prevent_audit_log_mutation()")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_simplify_membership_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Connexion refusée'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('SELECT_COMPANY', 'Changement de dépôt'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('FORECAST', 'Prévision')], max_length=30)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='companies.company')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='audit_company_date_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_date_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_date_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx')],
            },
        ),
        migrations.RunPython(protect_audit_logs, remove_audit_protection),
    ]
